### ISSUE TITLE
ERROR: Icons cannot be found 

### ISSUE THREAD

**Issue by xiaoyongzhu** [GetStream/react-native-example#6]
When I try to run the app, it has this error message:
```
2:36:40 PM: Error: 'assets/images/icon.png' could not be found, because 'assets/images' is not a subdirectory of any of the roots  ('C:\Users\xiaoyzhu\react-native-example')
2:36:40 PM:     at C:\Users\xiaoyzhu\react-native-example\node_modules\metro\src\Assets\index.js:190:11
2:36:40 PM:     at Generator.next (<anonymous>)
2:36:40 PM:     at step (C:\Users\xiaoyzhu\react-native-example\node_modules\metro\src\Assets\index.js:327:347)
2:36:40 PM:     at C:\Users\xiaoyzhu\react-native-example\node_modules\metro\src\Assets\index.js:327:507
2:36:55 PM: Stopping packager...
2:36:55 PM: Packager stopped.
```
Maybe the folder structure is incorrect?

**Comment by xiaoyongzhu** [comment]
Looks like this issue is solved when I have installed the stream client package... close it
